In [3]:
import torch

In [ ]:
with open("/Users/tusharsingharoy/Downloads/the-verdict.txt","r", encoding="utf-8") as f:
    raw_text=f.read()
print(len(raw_text))

20479


## Tokenized the Text

In [5]:
import re
token=re.split(r'([,.:;?"\s)]|--|\s)',raw_text)
print(token)
print(f"Text Size :{len(raw_text)}")
print(f"Total number of token :{len(token)}")
token_e_strip = [item.strip() for item in token if item.strip()]   ## item.strip() removes whitespace characters 
print(f"Total Number of teken without whitespace {len(token_e_strip)}")
uni_token=list(set(token_e_strip))    ## Store only the unique text
print(f"Total Number of unique token {len(uni_token)}")
uni_token=sorted(uni_token)

['I', ' ', 'HAD', ' ', 'always', ' ', 'thought', ' ', 'Jack', ' ', 'Gisburn', ' ', 'rather', ' ', 'a', ' ', 'cheap', ' ', 'genius', '--', 'though', ' ', 'a', ' ', 'good', ' ', 'fellow', ' ', 'enough', '--', 'so', ' ', 'it', ' ', 'was', ' ', 'no', ' ', 'great', ' ', 'surprise', ' ', 'to', ' ', 'me', ' ', 'to', ' ', 'hear', ' ', 'that', ',', '', ' ', 'in', ' ', 'the', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory', ',', '', ' ', 'he', ' ', 'had', ' ', 'dropped', ' ', 'his', ' ', 'painting', ',', '', ' ', 'married', ' ', 'a', ' ', 'rich', ' ', 'widow', ',', '', ' ', 'and', ' ', 'established', ' ', 'himself', ' ', 'in', ' ', 'a', ' ', 'villa', ' ', 'on', ' ', 'the', ' ', 'Riviera', '.', '', ' ', '(Though', ' ', 'I', ' ', 'rather', ' ', 'thought', ' ', 'it', ' ', 'would', ' ', 'have', ' ', 'been', ' ', 'Rome', ' ', 'or', ' ', 'Florence', '.', '', ')', '', '\n', '', '\n', '', '"', 'The', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory', '"', '', '--', 'that', ' ', 'was', ' ', 'what', '

In [6]:
vocab={token:integer for integer,token in enumerate(uni_token)}

In [7]:
vocab.items()

dict_items([('"', 0), ("'", 1), ("'Are", 2), ("'It's", 3), ("'coming'", 4), ("'done'", 5), ("'subject", 6), ("'technique'", 7), ("'way", 8), ('(I', 9), ('(Though', 10), (')', 11), (',', 12), ('--', 13), ('.', 14), (':', 15), (';', 16), ('?', 17), ('A', 18), ('Ah', 19), ('Among', 20), ('And', 21), ('Arrt', 22), ('As', 23), ('At', 24), ('Be', 25), ('Begin', 26), ('Burlington', 27), ('But', 28), ('By', 29), ('Carlo', 30), ('Chicago', 31), ('Claude', 32), ('Come', 33), ('Croft', 34), ('Destroyed', 35), ('Devonshire', 36), ("Don't", 37), ('Dubarry_', 38), ('Emperors', 39), ('Florence', 40), ('For', 41), ('Gallery', 42), ('Gideon', 43), ('Gisburn', 44), ('Gisburn!', 45), ("Gisburn's", 46), ('Gisburns', 47), ('Grafton', 48), ('Greek', 49), ('Grindle', 50), ("Grindle's", 51), ('Grindles', 52), ('HAD', 53), ('Had', 54), ('Hang', 55), ('Has', 56), ('He', 57), ('Her', 58), ('Hermia', 59), ("Hermia's", 60), ('His', 61), ('How', 62), ('I', 63), ("I'd", 64), ("I'll", 65), ("I've", 66), ('If', 67), (

## Printing frist 30 token with token ID'S

In [8]:
for i,item in enumerate(vocab.items()):
    print(item)
    if(i==30):
        break

('"', 0)
("'", 1)
("'Are", 2)
("'It's", 3)
("'coming'", 4)
("'done'", 5)
("'subject", 6)
("'technique'", 7)
("'way", 8)
('(I', 9)
('(Though', 10)
(')', 11)
(',', 12)
('--', 13)
('.', 14)
(':', 15)
(';', 16)
('?', 17)
('A', 18)
('Ah', 19)
('Among', 20)
('And', 21)
('Arrt', 22)
('As', 23)
('At', 24)
('Be', 25)
('Begin', 26)
('Burlington', 27)
('But', 28)
('By', 29)
('Carlo', 30)


## SimpleTokenizer

In [9]:
class SimpleTokenizer:
    def __init__(self,vocab):
        self.str_to_int=vocab
        self.int_to_str = {i:s for s,i in vocab.items()}
    
    def encoder(self,text):
        token=re.split(r'([,;:".}{]?|--|\s)',text)
        token=[item.strip() for item in token if item.strip()]
        token_ids=[self.str_to_int[s] for s in token]
        return token_ids
    
    def decoder(self,ids):
        text = " ".join([self.int_to_str[i] for i in ids])
         # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [10]:
# verdict_tokenizer = SimpleTokenizer(vocab)
# ids=verdict_tokenizer.encoder(raw_text)

## Add <|endoftext|> 
- Help to join to sentence 

In [11]:
text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."
text=" <|endoftext|> ".join((text1,text2))
print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


### BYTE PAIR ENCODING (BPE)   [BY using tiktoken]

In [12]:
# pip install tiktoken
import tiktoken as tik
model=["gpt2","gpt3","gpt4"]
gpt_vocab=[tik.get_encoding("gpt2"),tik.get_encoding("p50k_base"),tik.get_encoding("cl100k_base")]

In [13]:
for i, (model_name, vocab) in enumerate(zip(model, gpt_vocab)):
    print(f"The vocabulary size for {model_name} is: {vocab.n_vocab}")
    

The vocabulary size for gpt2 is: 50257
The vocabulary size for gpt3 is: 50281
The vocabulary size for gpt4 is: 100277


## DataLoader

In [14]:
from torch.utils.data import Dataset, DataLoader


In [15]:
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]
        

In [16]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):
    
    tokenizer=tik.get_encoding("gpt2")
    
    dataset=GPTDatasetV1(txt, tokenizer, max_length, stride)
    
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [17]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=3, max_length=4, stride=1, shuffle=False
)


In [18]:

for input_ids, target_ids in dataloader:
    print("Input IDs:", input_ids)
    print("Target IDs:", target_ids)
    break

Input IDs: tensor([[  40,  367, 2885, 1464],
        [ 367, 2885, 1464, 1807],
        [2885, 1464, 1807, 3619]])
Target IDs: tensor([[ 367, 2885, 1464, 1807],
        [2885, 1464, 1807, 3619],
        [1464, 1807, 3619,  402]])


### CREATING TOKEN EMBEDDINGS

In [19]:
vocab_size=6
output_dim=3

torch.manual_seed(123)
#####====>  IMP: embedding_layer  is not a list of tensor 
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)  ## Create some random weights 
print(embedding_layer.weight)    ## PrInt that random weights
a=embedding_layer.weight       ## It is a list of tensor


Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [20]:
print(embedding_layer(torch.tensor([3])))   ## print the 4th row of the embedding weight

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


### POSITIONAL EMBEDDINGS (ENCODING WORD POSITIONS)

In [21]:
## Let craete the embedding as like GPT 2
vocab_size=50257
output_dim=256

token_embedding_layer=torch.nn.Embedding(vocab_size,output_dim)

In [22]:
print(token_embedding_layer.weight)
print(token_embedding_layer.weight.shape)

Parameter containing:
tensor([[-2.1338,  1.0524, -0.3885,  ...,  0.2461,  1.2119,  0.3171],
        [ 1.2277, -0.4297, -2.2121,  ..., -0.1640, -0.3348, -0.0221],
        [ 1.3382,  0.2706,  0.5071,  ...,  0.0175, -2.1517,  0.3924],
        ...,
        [-1.4889, -1.2456,  1.8034,  ..., -0.6392, -1.4939,  0.3614],
        [-1.0703,  0.2795, -0.2637,  ..., -0.2810, -1.4755, -0.1183],
        [-0.0071,  0.4982, -0.3319,  ...,  0.4970,  0.9365, -0.2091]],
       requires_grad=True)
torch.Size([50257, 256])


In [23]:
dataloader=dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=4,
    stride=4, shuffle=False)
count=0
for input_id,target_id in dataloader:
    print(f"Input ID : {input_id}")
    print(f"Input ID : {target_id}")
    count=count+1
    

print(count)  ## len(token_ids) = num_samples × stride + max_length = 1280 × 4 + 4 = 5124

Input ID : tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Input ID : tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])
Input ID : tensor([[  287,   262,  6001,   286],
        [  465, 13476,    11,   339],
        [  550,  5710,   465, 12036],
        [   11,  6405,   257,  5527],
        [27075,    11,   290,  4920],
        [ 2241,   287,   257,  4489],
        [   64,   319,   262, 34686],
        [41976,    13,   357, 10915]])
Input ID : tensor([[  262,  6001,   286,   465],
   

## Positional Embedding

In [24]:
context_length = 4
output_dim=256
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [25]:
print(pos_embedding_layer.weight)
pos_embeddings = pos_embedding_layer(torch.arange(4))
print(pos_embeddings.shape)

Parameter containing:
tensor([[ 1.7375, -0.5620, -0.6303,  ..., -0.2277,  1.5748,  1.0345],
        [ 1.6423, -0.7201,  0.2062,  ...,  0.4118,  0.1498, -0.4628],
        [-0.4651, -0.7757,  0.5806,  ...,  1.4335, -0.4963,  0.8579],
        [-0.6754, -0.4628,  1.4323,  ...,  0.8139, -0.7088,  0.4827]],
       requires_grad=True)
torch.Size([4, 256])


In [26]:
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [27]:
input_embeddings = token_embeddings + pos_embeddings
print(f"Shape of token Embedding  {token_embeddings.shape}")
print(f"Shape of pos Embedding  {pos_embeddings.shape}")   ## Braodcast the row
print(f"Shape of input Embedding  {input_embeddings.shape}")


Shape of token Embedding  torch.Size([8, 4, 256])
Shape of pos Embedding  torch.Size([4, 256])
Shape of input Embedding  torch.Size([8, 4, 256])


##  ATTENTION MECHANISM

In [28]:
import torch

input = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)
# print(input[2])

In [29]:
## Let print attention score
query =input[2] # start

def atten_score(input,query):
    att_score=torch.empty(input.shape[0])
    for i,x_i in enumerate(input):
        att_score[i] =torch.dot(x_i,query)   ## Simple attention only by dot product 
    return att_score
att_score=atten_score(input,query)
print(att_score)
    

tensor([0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605])


<strong>The main goal behind the normalization</strong> is to obtain attention weights
  that sum up to 1.

  This normalization is a convention that is useful for interpretation and for
  maintaining training stability in an LLM

  Here's a straightforward method for achieving this
  normalization step:


In [30]:
attn_weights_2_tmp = att_score / att_score.sum()

print("Attention weights:", attn_weights_2_tmp)
print("Sum:", attn_weights_2_tmp.sum())

Attention weights: tensor([0.1454, 0.2277, 0.2248, 0.1280, 0.1104, 0.1637])
Sum: tensor(1.)


In [31]:
## change into softmax attention
def softmax_att(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)
atten_soft_score=softmax_att(att_score)
print(f"Attention weight after softmax = {atten_soft_score} ")

Attention weight after softmax = tensor([0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565]) 


## Attention Matrix

In [32]:
import time
start = time.time()  ## Starting time
att_table=torch.empty(6,6) ## Create an empty matrix
for i,x_i in enumerate(input):
    query=input[i]
    att_table[i]=atten_score(input,query)
time.sleep(1)  ## Increase 1 Sec
end = time.time()  ## end time
print(att_table)
print(f"Time taken to run the loop {end-start} Sec")

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
Time taken to run the loop 1.0068104267120361 Sec


In [33]:
## Attention Score by using Matrix Multiplication
start=time.time()
attn_table=input @ input.T
time.sleep(1)
end=time.time()
print(att_table)
print(f"Time taken to run the loop {end-start} Sec")


tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
Time taken to run the loop 1.0010499954223633 Sec


## Applying direct softmax

In [34]:
## Attention weight matrix
attn_weights = torch.softmax(attn_table, dim=-1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [35]:
## Now find all the context vector
all_context_vec=attn_weights @ input
print(all_context_vec)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


## IMPLEMENTING SELF ATTENTION WITH TRAINABLE WEIGHTS(Key ,Query,Value)

In [36]:
print(input.shape)
d_in=input.shape[1]
d_out=2

torch.Size([6, 3])


In [37]:
# torch.manual_seed(123)
w_query=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
w_key=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
w_value=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)

In [38]:
print(f"w_query Matrix {w_query} ")
print(f"w_key Matrix {w_key} ")
print(f"w_value Matrix {w_value} ")

w_query Matrix Parameter containing:
tensor([[0.5628, 0.2308],
        [0.4156, 0.0014],
        [0.8157, 0.1645]]) 
w_key Matrix Parameter containing:
tensor([[0.4039, 0.8877],
        [0.3615, 0.7642],
        [0.2305, 0.5352]]) 
w_value Matrix Parameter containing:
tensor([[0.1136, 0.5045],
        [0.2898, 0.9282],
        [0.8003, 0.9874]]) 


In [39]:
## Let's take the x2 from the and find the corresponding Key ,query and value 
x_2=input[1]   ## this is for single value x2
q_2=x_2 @ w_query
v_2=x_2 @ w_key
print(q_2)

tensor([1.2095, 0.2367])


In [40]:
## Now find key , query and value for the all inputs
keys=input @ w_key
values=input @ w_value
queries=input @ w_query

print("keys Matrix:", keys)

print("values Matrix:", values)

print("queries Matrix:", queries)

keys Matrix: tensor([[0.4331, 0.9727],
        [0.6888, 1.5064],
        [0.6850, 1.4981],
        [0.3746, 0.8152],
        [0.4244, 0.9281],
        [0.4361, 0.9502]])
values Matrix: tensor([[0.8046, 1.2349],
        [0.8428, 1.7367],
        [0.8233, 1.7084],
        [0.4572, 0.9752],
        [0.2399, 0.7192],
        [0.6777, 1.3108]])
queries Matrix: tensor([[1.0304, 0.2459],
        [1.2095, 0.2367],
        [1.1962, 0.2380],
        [0.6341, 0.1059],
        [0.6189, 0.1945],
        [0.8093, 0.1031]])


In [41]:
## Let find the attention score for the x2 dot(q_2,k_2)
key_2=keys[1]
att_s2=q_2.dot(key_2)
print(att_s2)

tensor(1.1897)


In [42]:
## finding the attention score for the all the iputs
attn_scores = queries @ keys.T # omega
print(attn_scores)

tensor([[0.6854, 1.0800, 1.0741, 0.5864, 0.6655, 0.6830],
        [0.7541, 1.1897, 1.1832, 0.6460, 0.7331, 0.7525],
        [0.7495, 1.1824, 1.1760, 0.6421, 0.7286, 0.7479],
        [0.3776, 0.5962, 0.5929, 0.3238, 0.3674, 0.3771],
        [0.4572, 0.7193, 0.7153, 0.3904, 0.4432, 0.4547],
        [0.4508, 0.7128, 0.7089, 0.3872, 0.4392, 0.4510]])


In [43]:
d_k = keys.shape[-1]
attn_weights = torch.softmax(attn_scores / d_k**0.5,dim=-1)   ## divided by sqrt of key dimension
print(attn_weights)
print(d_k)

tensor([[0.1526, 0.2017, 0.2008, 0.1422, 0.1504, 0.1523],
        [0.1509, 0.2054, 0.2044, 0.1398, 0.1487, 0.1508],
        [0.1510, 0.2051, 0.2042, 0.1400, 0.1488, 0.1509],
        [0.1591, 0.1857, 0.1852, 0.1531, 0.1579, 0.1590],
        [0.1576, 0.1897, 0.1891, 0.1503, 0.1560, 0.1573],
        [0.1574, 0.1895, 0.1890, 0.1505, 0.1562, 0.1575]])
2


## IMPLEMENTING A COMPACT SELF ATTENTION PYTHON CLASS

In [44]:
import torch.nn as nn

class SelfAttention(nn.Module):
    def __init__(self,d_in,d_out):
        super().__init__()
        self.w_query=nn.Parameter(torch.rand(d_in,d_out))
        self.w_key=nn.Parameter(torch.rand(d_in,d_out))
        self.w_value=nn.Parameter(torch.rand(d_in,d_out))
    
    def forward(self,x):
        query =x @ self.w_query
        key=x @ self.w_key
        value=x @ self.w_value
        
        att_score=query @ keys.T 
        att_weight=torch.softmax(att_score/key.shape[-1]**0.5,dim=-1)
        
        context_vec=att_weight @ value
        
        return context_vec

# print(input.shape)

In [45]:
Self_att_cls = SelfAttention(d_in, d_out)
print(Self_att_cls(input))

tensor([[0.7022, 1.0457],
        [0.7208, 1.0681],
        [0.7197, 1.0668],
        [0.6919, 1.0333],
        [0.6819, 1.0209],
        [0.7049, 1.0490]], grad_fn=<MmBackward0>)


 ## CAUSAL ATTENTION

In [46]:
attn_weights

tensor([[0.1526, 0.2017, 0.2008, 0.1422, 0.1504, 0.1523],
        [0.1509, 0.2054, 0.2044, 0.1398, 0.1487, 0.1508],
        [0.1510, 0.2051, 0.2042, 0.1400, 0.1488, 0.1509],
        [0.1591, 0.1857, 0.1852, 0.1531, 0.1579, 0.1590],
        [0.1576, 0.1897, 0.1891, 0.1503, 0.1560, 0.1573],
        [0.1574, 0.1895, 0.1890, 0.1505, 0.1562, 0.1575]])

In [47]:
## applying causal attention
mask=torch.tril(torch.ones(attn_weights.shape))
print(f"MASK :{mask}")
causal_weight=mask*attn_weights
print(f"CAUSAL WEIGHT :{causal_weight}")
causal_norm=causal_weight/causal_weight.sum(dim=-1,keepdim=True)
print(causal_norm) ## ReNormailazation

MASK :tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])
CAUSAL WEIGHT :tensor([[0.1526, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1509, 0.2054, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1510, 0.2051, 0.2042, 0.0000, 0.0000, 0.0000],
        [0.1591, 0.1857, 0.1852, 0.1531, 0.0000, 0.0000],
        [0.1576, 0.1897, 0.1891, 0.1503, 0.1560, 0.0000],
        [0.1574, 0.1895, 0.1890, 0.1505, 0.1562, 0.1575]])
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4236, 0.5764, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2695, 0.3661, 0.3644, 0.0000, 0.0000, 0.0000],
        [0.2329, 0.2718, 0.2712, 0.2242, 0.0000, 0.0000],
        [0.1870, 0.2251, 0.2244, 0.1784, 0.1851, 0.0000],
        [0.1574, 0.1895, 0.1890, 0.1505, 0.1562, 0.1575]])


## NOTE:
- But after re Norm still there are some effect of previous value so , change the 0 element into -inf before applying softmax

In [48]:
mask=torch.triu(torch.ones(attn_weights.shape),diagonal=1)
causal_weight=causal_weight.masked_fill(mask.bool(),-torch.inf)

In [49]:
causal_weight

tensor([[0.1526,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.1509, 0.2054,   -inf,   -inf,   -inf,   -inf],
        [0.1510, 0.2051, 0.2042,   -inf,   -inf,   -inf],
        [0.1591, 0.1857, 0.1852, 0.1531,   -inf,   -inf],
        [0.1576, 0.1897, 0.1891, 0.1503, 0.1560,   -inf],
        [0.1574, 0.1895, 0.1890, 0.1505, 0.1562, 0.1575]])

In [50]:
## Now apply softmax
C_attn_wgt=torch.softmax(causal_weight/keys.shape[-1]**0.5 ,dim=-1)

In [51]:
C_attn_wgt

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4904, 0.5096, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3250, 0.3376, 0.3374, 0.0000, 0.0000, 0.0000],
        [0.2479, 0.2526, 0.2526, 0.2469, 0.0000, 0.0000],
        [0.1984, 0.2030, 0.2029, 0.1974, 0.1982, 0.0000],
        [0.1656, 0.1694, 0.1693, 0.1648, 0.1654, 0.1656]])

## DROPOUT

In [52]:
import torch
one_tensor = torch.ones(6, 6)
print(one_tensor)


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


When applying dropout to an attention weight matrix with a rate of 50%, half of the
elements in the matrix are randomly set to zero. 

To compensate for the reduction in active
elements, the values of the remaining elements in the matrix are scaled up by a factor of
1/0.5 =2. 

This scaling is crucial to maintain the overall balance of the attention weights,
ensuring that the average influence of the attention mechanism remains consistent during
both the training and inference phases.


In [53]:
dropout=torch.nn.Dropout(0.5)
print(dropout(one_tensor))

tensor([[2., 0., 2., 0., 0., 0.],
        [0., 2., 0., 0., 2., 0.],
        [0., 0., 2., 2., 0., 0.],
        [0., 2., 0., 0., 0., 0.],
        [2., 0., 0., 0., 2., 2.],
        [0., 2., 0., 2., 2., 0.]])


In [54]:
import torch.nn as nn

class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.w_query = nn.Linear(d_in, d_out, bias=qkv_bias) ## output = x @ W_query.T + b_query
        self.w_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.w_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
        self.dropout = nn.Dropout(dropout) if isinstance(dropout, float) else dropout  # expects a nn.Dropout instance or float

    def forward(self, x):
        b, num_token, d_in = x.shape   ## B is the number of batches 
        query = self.w_query(x)
        key = self.w_key(x)
        value = self.w_value(x)

        att_score = query @ key.transpose(1, 2)  #keys.shape = (batch_size, seq_len, d_out) ==>keys.transpose(1, 2).shape = (batch_size, d_out, seq_len)
        att_score.masked_fill
        att_score = att_score.masked_fill(
            self.mask[:num_token, :num_token].bool(), float('-inf')
        ) 
        attn_weights = torch.softmax(
            att_score / key.shape[-1]**0.5, dim=-1
        )
        attn_weights = self.dropout(attn_weights)

        context_vec = attn_weights @ value
        return context_vec

Causal_attn = CausalAttention(3, 2, 6, 0.0)   ## Context_length = Number of token
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)
batch = torch.stack((inputs, inputs), dim=0)  ## 2 batch
Causal_attn(batch)

tensor([[[ 0.5027, -0.1412],
         [ 0.5950, -0.0196],
         [ 0.6235,  0.0245],
         [ 0.5644,  0.0351],
         [ 0.5171,  0.0736],
         [ 0.5124,  0.0605]],

        [[ 0.5027, -0.1412],
         [ 0.5950, -0.0196],
         [ 0.6235,  0.0245],
         [ 0.5644,  0.0351],
         [ 0.5171,  0.0736],
         [ 0.5124,  0.0605]]], grad_fn=<UnsafeViewBackward0>)

## MultiHead Attention

In [ ]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        self.d_out=d_out
        self.num_heads=num_heads
        self.head_dim=d_out//num_heads
        
        self.w_query=nn.Linear(d_in,d_out,bias=qkv_bias)
        self.w_key=nn.Linear(d_in,d_out,bias=qkv_bias)
        self.w_value=nn.Linear(d_in,d_out,bias=qkv_bias)
        self.out_proj = nn.Linear(d_out, d_out)  # Linear layer to combine head outputs
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            "mask",
            torch.triu(torch.ones(context_length, context_length),
                       diagonal=1)
        )
        
    def forward(self, x):
        b, num_token, d_in = x.shape
        key=self.w_key(x)
        query=self.w_query(x)
        value=self.w_value(x)
        
            # Unroll last dim: (b, num_tokens, d_out) -> (b, num_tokens, num_heads, head_dim)
        keys=key.view(b,num_token,self.num_heads,self.head_dim)
        queries=query.view(b,num_token,self.num_heads,self.head_dim)
        values=value.view(b,num_token,self.num_heads,self.head_dim)
        
            # Transpose: (b, num_tokens, num_heads, head_dim) -> (b, num_heads, num_tokens, head_dim)
            
        # keys=keys.veiw(b,self.num_heads,num_token,self.head_dim)
        # values=values.veiw(b,self.num_heads,num_token,self.head_dim)
        # queries=queries.veiw(b,self.num_heads,num_token,self.head_dim)
            
        keys = keys.transpose(1, 2)
        queries = queries.transpose(1, 2)
        values = values.transpose(1, 2)    ## same as above
        
        att_score=queries @ keys.transpose(2,3)  # Dot product for each head
        mask_bool = self.mask.bool()[:num_token, :num_token]
        att_score.masked_fill_(mask_bool,-torch.inf)           
        att_weight=torch.softmax(att_score/key.shape[-1]**0.5 ,dim=-1)
        
        att_weight=self.dropout(att_weight)
        
        context_vec=att_weight @ values 
        
        ## Back to original shape  : (b, num_tokens, num_heads, head_dim)
        
        context_vec = context_vec.view(b, num_token, self.d_out)
        
        context_vec = self.out_proj(context_vec) 
        return context_vec 
        

In [69]:
## Apply the above class 
inputs = torch.tensor(
    [[0.67, 0.78, 0.79, 0.70, 0.14, 0.66],  # Row 1
     [0.87, 0.34, 0.74, 0.12, 0.54, 0.35],  # Row 2
     [0.77, 0.25, 0.10, 0.05, 0.80, 0.55]]  # Row 3
)

input=torch.stack((inputs,inputs),dim=0)
d_out=6
batch,context_len,d_in=input.shape
Muti_head_att=MultiHeadAttention(d_in, d_out, context_length, 0.0, num_heads=2)
cont_vec = Muti_head_att(input)
print(cont_vec)

tensor([[[ 0.0870, -0.3135, -0.2915,  0.2975,  0.0163, -0.1661],
         [ 0.1365, -0.0593, -0.2743,  0.1447,  0.0208, -0.4146],
         [ 0.4248,  0.1467, -0.2342, -0.2936, -0.2910, -0.7645]],

        [[ 0.0870, -0.3135, -0.2915,  0.2975,  0.0163, -0.1661],
         [ 0.1365, -0.0593, -0.2743,  0.1447,  0.0208, -0.4146],
         [ 0.4248,  0.1467, -0.2342, -0.2936, -0.2910, -0.7645]]],
       grad_fn=<ViewBackward0>)
